- hosts: davmail
  sudo: yes
  roles:
    - role: openssh
    - role: pf
      pf_open_ports:
        - ssh
        - '{{ davmail_pop_port }}'
    - role: davmail
    - role: monit
      monit_check_processes:
        - name: davmail
          pidfile: '{{ davmail_pid_file }}'
          start: /usr/sbin/service davmail start
          stop: /usr/sbin/service davmail stop
    - role: aliases
