- name: install davmail package
  pkgng: name=davmail
  sudo: yes

- name: copy davmail config
  template: src=davmail.properties.j2
            dest=/usr/local/etc/davmail.properties
            owner=root group=wheel mode=0644
  sudo: yes
  notify: restart davmail

- name: enable davmail on boot
  service: name=davmail state=started enabled=yes
  sudo: yes

- name: start davmail
  service: name=davmail state=started
  sudo: yes
