- name: install davmail package
  pkgng: name=davmail
  sudo: yes

- name: copy davmail config
  template: src=davmail.properties.j2
            dest=/usr/local/etc/davmail.properties
            owner=root group=wheel mode=0644
  sudo: yes
  notify: restart davmail

- name: protect davmail directory
  file: path=/usr/local/etc/davmail state=directory mode=0700
  sudo: yes

- name: protect davmail cert
  file: path={{ davmail_pkcs12_key }} state=file mode=0600
  sudo: yes

- name: protect davmail properties
  file: path=/usr/local/etc/davmail.properties state=file mode=0600
  sudo: yes

- name: enable davmail on boot
  service: name=davmail state=started enabled=yes
  sudo: yes

- name: start davmail
  service: name=davmail state=started
  sudo: yes
